import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/provider";
import { ChakraBaseProvider } from "@chakra-ui/react";
import Sidebar from "@/components/Sidebar";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="p-3 md:flex md:p-10 md:ml-20">
				<Providers>
					<Sidebar />
					<div className="w-full">{children}</div>
					<Toaster />
				</Providers>
			</body>
		</html>
	);
}
